[workspace]
members = [
    "controlled-transfer-contract",
    "test-nep141-token",
    "near-workspaces-integration-test"
]
resolver = "2"

[profile.release]
codegen-units=1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true